// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Appeal
{
    public int AppealId { get; set; }

    public int? AdjustmentId { get; set; }

    public int TeamId { get; set; }

    public string Message { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Status { get; set; }

    public int? ReviewedById { get; set; }

    public string AdminResponse { get; set; }

    public DateTime? ReviewedAt { get; set; }

    public string AppealType { get; set; }

    public string Reason { get; set; }

    public int? SubmissionId { get; set; }

    public int? JudgeId { get; set; }

    public virtual PenaltiesBonuse Adjustment { get; set; }

    public virtual User Judge { get; set; }

    public virtual User ReviewedBy { get; set; }

    public virtual Submission Submission { get; set; }

    public virtual Team Team { get; set; }
}