// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Challenge
{
    public int ChallengeId { get; set; }

    public int HackathonId { get; set; }

    public int? UserId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string FilePath { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Status { get; set; }

    public int? TrackId { get; set; }

    public virtual Hackathon Hackathon { get; set; }

    public virtual Track Track { get; set; }

    public virtual User User { get; set; }
}