// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Chapter
{
    public int ChapterId { get; set; }

    public string ChapterName { get; set; }

    public string Description { get; set; }

    public int? ChapterLeaderId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<MentorAssignment> MentorAssignments { get; set; } = new List<MentorAssignment>();

    public virtual ICollection<Team> Teams { get; set; } = new List<Team>();
}