// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class ChatGroup
{
    public int ChatGroupId { get; set; }

    public int MentorId { get; set; }

    public int TeamId { get; set; }

    public int HackathonId { get; set; }

    public string GroupName { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? LastMessageAt { get; set; }

    public virtual ICollection<ChatMessage> ChatMessages { get; set; } = new List<ChatMessage>();

    public virtual Hackathon Hackathon { get; set; }

    public virtual User Mentor { get; set; }

    public virtual Team Team { get; set; }
}