// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class ChatMessage
{
    public int MessageId { get; set; }

    public int ChatGroupId { get; set; }

    public int SenderId { get; set; }

    public string Content { get; set; }

    public DateTime SentAt { get; set; }

    public bool IsRead { get; set; }

    public virtual ChatGroup ChatGroup { get; set; }

    public virtual ICollection<ChatMessageRead> ChatMessageReads { get; set; } = new List<ChatMessageRead>();

    public virtual User Sender { get; set; }
}