// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class ChatMessageRead
{
    public int ChatMessageReadId { get; set; }

    public int MessageId { get; set; }

    public int UserId { get; set; }

    public DateTime ReadAt { get; set; }

    public virtual ChatMessage Message { get; set; }

    public virtual User User { get; set; }
}