// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class CriterionDetail
{
    public int CriterionDetailId { get; set; }

    public int CriteriaId { get; set; }

    public string Description { get; set; }

    public int MaxScore { get; set; }

    public virtual Criterion Criteria { get; set; }
}