// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class FinalQualification
{
    public int QualificationId { get; set; }

    public int TeamId { get; set; }

    public int GroupId { get; set; }

    public string Name { get; set; }

    public int PhaseId { get; set; }

    public int TrackId { get; set; }

    public DateTime? QualifiedAt { get; set; }

    public virtual Group Group { get; set; }

    public virtual HackathonPhase Phase { get; set; }

    public virtual Team Team { get; set; }

    public virtual Track Track { get; set; }
}