// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Group
{
    public int GroupId { get; set; }

    public int TrackId { get; set; }

    public string GroupName { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<FinalQualification> FinalQualifications { get; set; } = new List<FinalQualification>();

    public virtual ICollection<GroupTeam> GroupTeams { get; set; } = new List<GroupTeam>();
}