// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class GroupTeam
{
    public int GroupTeamId { get; set; }

    public int GroupId { get; set; }

    public int? Rank { get; set; }

    public int TeamId { get; set; }

    public DateTime? JoinedAt { get; set; }

    public virtual Group Group { get; set; }

    public virtual Team Team { get; set; }
}