// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class HackathonRegistration
{
    public int RegistrationId { get; set; }

    public int HackathonId { get; set; }

    public int TeamId { get; set; }

    public string Link { get; set; }

    public DateTime RegisteredAt { get; set; }

    public string Status { get; set; }

    public DateTime? CancelledAt { get; set; }

    public string CancelReason { get; set; }

    public virtual Hackathon Hackathon { get; set; }

    public virtual Team Team { get; set; }
}