// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class HackathonPhase
{
    public int PhaseId { get; set; }

    public int? HackathonId { get; set; }

    public string PhaseName { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public virtual Hackathon Hackathon { get; set; }

    public virtual ICollection<PhaseChallenge> PhaseChallenges { get; set; } = new List<PhaseChallenge>();

    public virtual ICollection<TeamChallenge> TeamChallenges { get; set; } = new List<TeamChallenge>();
}