// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Hackathon
{
    public int HackathonId { get; set; }

    public string Name { get; set; }

    public int SeasonId { get; set; }

    public string Theme { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public int? CreatedBy { get; set; }

    public string Status { get; set; }

    public virtual ICollection<HackathonPhase> HackathonPhases { get; set; } = new List<HackathonPhase>();

    public virtual ICollection<Prize> Prizes { get; set; } = new List<Prize>();

    public virtual ICollection<ScheduleEvent> ScheduleEvents { get; set; } = new List<ScheduleEvent>();

    public virtual Season Season { get; set; }
}