// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class JudgeAssignment
{
    public int AssignmentId { get; set; }

    public int JudgeId { get; set; }

    public int HackathonId { get; set; }

    public int? PhaseId { get; set; }

    public int? TrackId { get; set; }

    public DateTime AssignedAt { get; set; }

    public string Status { get; set; }

    public virtual Hackathon Hackathon { get; set; }

    public virtual User Judge { get; set; }

    public virtual HackathonPhase Phase { get; set; }

    public virtual Track Track { get; set; }
}