// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class MentorVerification
{
    public int Id { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Position { get; set; }

    public string Cv { get; set; }

    public string ReasonToBecomeMentor { get; set; }

    public string RejectReason { get; set; }

    public string Status { get; set; }

    public int HackathonId { get; set; }

    public int UserId { get; set; }

    public int? ChapterId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Chapter Chapter { get; set; }

    public virtual Hackathon Hackathon { get; set; }

    public virtual User User { get; set; }
}