// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class PartnerProfile
{
    public int PartnerProfileId { get; set; }

    public int UserId { get; set; }

    public string CompanyName { get; set; }

    public string LogoUrl { get; set; }

    public string Website { get; set; }

    public string Description { get; set; }

    public virtual User User { get; set; }
}