// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class PenaltiesBonuse
{
    public int AdjustmentId { get; set; }

    public int TeamId { get; set; }

    public string Type { get; set; }

    public decimal Points { get; set; }

    public string Reason { get; set; }

    public DateTime CreatedAt { get; set; }

    public int PhaseId { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<Appeal> Appeals { get; set; } = new List<Appeal>();

    public virtual User CreatedByNavigation { get; set; }

    public virtual HackathonPhase Phase { get; set; }

    public virtual Team Team { get; set; }
}