// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class PhaseChallenge
{
    public int PhaseChallengeId { get; set; }

    public int PhaseId { get; set; }

    public int ChallengeId { get; set; }

    public DateTime AssignedAt { get; set; }

    public virtual Challenge Challenge { get; set; }

    public virtual HackathonPhase Phase { get; set; }
}