// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Ranking
{
    public int RankingId { get; set; }

    public int HackathonId { get; set; }

    public int TeamId { get; set; }

    public decimal TotalScore { get; set; }

    public int? Rank { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Hackathon Hackathon { get; set; }

    public virtual Team Team { get; set; }
}