// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class ScheduleEvent
{
    public int EventId { get; set; }

    public int HackathonId { get; set; }

    public int? PhaseId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public string Location { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string Description { get; set; }

    public virtual Hackathon Hackathon { get; set; }

    public virtual HackathonPhase Phase { get; set; }
}