// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class ScoreHistory
{
    public int HistoryId { get; set; }

    public int ScoreId { get; set; }

    public int SubmissionId { get; set; }

    public int JudgeId { get; set; }

    public int CriteriaId { get; set; }

    public int OldScore { get; set; }

    public string OldComment { get; set; }

    public DateTime ChangedAt { get; set; }

    public string ChangeReason { get; set; }

    public int? ChangedBy { get; set; }

    public virtual Criterion Criteria { get; set; }

    public virtual User Judge { get; set; }

    public virtual Score Score { get; set; }

    public virtual Submission Submission { get; set; }
}