// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Models;

public partial class SealDbContext : DbContext
{
    public SealDbContext(DbContextOptions<SealDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Appeal> Appeals { get; set; }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<Challenge> Challenges { get; set; }

    public virtual DbSet<Chapter> Chapters { get; set; }

    public virtual DbSet<ChatGroup> ChatGroups { get; set; }

    public virtual DbSet<ChatMessage> ChatMessages { get; set; }

    public virtual DbSet<ChatMessageRead> ChatMessageReads { get; set; }

    public virtual DbSet<Criterion> Criteria { get; set; }

    public virtual DbSet<FinalQualification> FinalQualifications { get; set; }

    public virtual DbSet<Group> Groups { get; set; }

    public virtual DbSet<GroupTeam> GroupTeams { get; set; }

    public virtual DbSet<Hackathon> Hackathons { get; set; }

    public virtual DbSet<HackathonPhase> HackathonPhases { get; set; }

    public virtual DbSet<HackathonRegistration> HackathonRegistrations { get; set; }

    public virtual DbSet<JudgeAssignment> JudgeAssignments { get; set; }

    public virtual DbSet<MentorAssignment> MentorAssignments { get; set; }

    public virtual DbSet<MentorVerification> MentorVerifications { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<PartnerProfile> PartnerProfiles { get; set; }

    public virtual DbSet<PenaltiesBonuse> PenaltiesBonuses { get; set; }

    public virtual DbSet<Prize> Prizes { get; set; }

    public virtual DbSet<PrizeAllocation> PrizeAllocations { get; set; }

    public virtual DbSet<Ranking> Rankings { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<ScheduleEvent> ScheduleEvents { get; set; }

    public virtual DbSet<Score> Scores { get; set; }

    public virtual DbSet<ScoreHistory> ScoreHistories { get; set; }

    public virtual DbSet<Season> Seasons { get; set; }

    public virtual DbSet<StudentVerification> StudentVerifications { get; set; }

    public virtual DbSet<Submission> Submissions { get; set; }

    public virtual DbSet<Team> Teams { get; set; }

    public virtual DbSet<TeamInvitation> TeamInvitations { get; set; }

    public virtual DbSet<TeamJoinRequest> TeamJoinRequests { get; set; }

    public virtual DbSet<TeamMember> TeamMembers { get; set; }

    public virtual DbSet<TeamTrackSelection> TeamTrackSelections { get; set; }

    public virtual DbSet<Track> Tracks { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Appeal>(entity =>
        {
            entity.HasKey(e => e.AppealId).HasName("PK__Appeals__BB684E108B9FCF5C");

            entity.Property(e => e.AppealId).HasColumnName("AppealID");
            entity.Property(e => e.AdjustmentId).HasColumnName("AdjustmentID");
            entity.Property(e => e.AppealType).HasMaxLength(20);
            entity.Property(e => e.JudgeId).HasColumnName("JudgeID");
            entity.Property(e => e.ReviewedById).HasColumnName("ReviewedByID");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.SubmissionId).HasColumnName("SubmissionID");
            entity.Property(e => e.TeamId).HasColumnName("TeamID");

            entity.HasOne(d => d.Adjustment).WithMany(p => p.Appeals)
                .HasForeignKey(d => d.AdjustmentId)
                .OnDelete(DeleteBehavior.SetNull);

            entity.HasOne(d => d.Judge).WithMany(p => p.AppealJudges).HasForeignKey(d => d.JudgeId);

            entity.HasOne(d => d.ReviewedBy).WithMany(p => p.AppealReviewedBies)
                .HasForeignKey(d => d.ReviewedById)
                .OnDelete(DeleteBehavior.SetNull);

            entity.HasOne(d => d.Submission).WithMany(p => p.Appeals).HasForeignKey(d => d.SubmissionId);

            entity.HasOne(d => d.Team).WithMany(p => p.Appeals)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__AuditLog__5E5499A87BCC98C1");

            entity.Property(e => e.LogId).HasColumnName("LogID");
            entity.Property(e => e.Action).HasMaxLength(200);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Challenge>(entity =>
        {
            entity.HasKey(e => e.ChallengeId).HasName("PK__Challeng__C7AC8128BFFF7E59");

            entity.Property(e => e.ChallengeId).HasColumnName("ChallengeID");
            entity.Property(e => e.FilePath).HasMaxLength(255);
            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.TrackId).HasColumnName("TrackID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Hackathon).WithMany(p => p.Challenges)
                .HasForeignKey(d => d.HackathonId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Track).WithMany(p => p.Challenges)
                .HasForeignKey(d => d.TrackId)
                .OnDelete(DeleteBehavior.SetNull);

            entity.HasOne(d => d.User).WithMany(p => p.Challenges)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity<Chapter>(entity =>
        {
            entity.HasKey(e => e.ChapterId).HasName("PK__Chapters__0893A34A1C668A63");

            entity.Property(e => e.ChapterId).HasColumnName("ChapterID");
            entity.Property(e => e.ChapterLeaderId).HasColumnName("ChapterLeaderID");
            entity.Property(e => e.ChapterName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.ChapterLeader).WithMany(p => p.Chapters)
                .HasForeignKey(d => d.ChapterLeaderId)
                .OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity<ChatGroup>(entity =>
        {
            entity.HasKey(e => e.ChatGroupId).HasName("PK__ChatGrou__435956F8BB412F63");

            entity.HasIndex(e => new { e.MentorId, e.TeamId, e.HackathonId }, "UQ_ChatGroups").IsUnique();

            entity.Property(e => e.ChatGroupId).HasColumnName("ChatGroupID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.GroupName).HasMaxLength(200);
            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.LastMessageAt).HasColumnType("datetime");
            entity.Property(e => e.MentorId).HasColumnName("MentorID");
            entity.Property(e => e.TeamId).HasColumnName("TeamID");

            entity.HasOne(d => d.Hackathon).WithMany(p => p.ChatGroups)
                .HasForeignKey(d => d.HackathonId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Mentor).WithMany(p => p.ChatGroups)
                .HasForeignKey(d => d.MentorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChatGroups_Mentors_MentorID");

            entity.HasOne(d => d.Team).WithMany(p => p.ChatGroups)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ChatMessage>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__ChatMess__C87C037C44EC8E5C");

            entity.HasIndex(e => e.ChatGroupId, "IX_ChatMessages_ChatGroups");

            entity.Property(e => e.MessageId).HasColumnName("MessageID");
            entity.Property(e => e.ChatGroupId).HasColumnName("ChatGroupID");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasMaxLength(2000);
            entity.Property(e => e.SenderId).HasColumnName("SenderID");
            entity.Property(e => e.SentAt).HasColumnType("datetime");

            entity.HasOne(d => d.ChatGroup).WithMany(p => p.ChatMessages).HasForeignKey(d => d.ChatGroupId);

            entity.HasOne(d => d.Sender).WithMany(p => p.ChatMessages)
                .HasForeignKey(d => d.SenderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChatMessages_Senders_SenderID");
        });

        modelBuilder.Entity<ChatMessageRead>(entity =>
        {
            entity.HasKey(e => e.ChatMessageReadId).HasName("PK__ChatMess__B741EF1F59574673");

            entity.HasIndex(e => new { e.MessageId, e.UserId }, "IX_ChatMessageReads_ChatMessages_Users");

            entity.HasIndex(e => new { e.MessageId, e.UserId }, "UQ_ChatMessageReads").IsUnique();

            entity.Property(e => e.ChatMessageReadId).HasColumnName("ChatMessageReadID");
            entity.Property(e => e.MessageId).HasColumnName("MessageID");
            entity.Property(e => e.ReadAt).HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Message).WithMany(p => p.ChatMessageReads).HasForeignKey(d => d.MessageId);

            entity.HasOne(d => d.User).WithMany(p => p.ChatMessageReads)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Criterion>(entity =>
        {
            entity.HasKey(e => e.CriteriaId).HasName("PK__Criteria__FE6ADB2D6ACB4700");

            entity.Property(e => e.CriteriaId).HasColumnName("CriteriaID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PhaseId).HasColumnName("PhaseID");
            entity.Property(e => e.TrackId).HasColumnName("TrackID");
            entity.Property(e => e.Weight).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Phase).WithMany(p => p.Criteria)
                .HasForeignKey(d => d.PhaseId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Track).WithMany(p => p.Criteria).HasForeignKey(d => d.TrackId);
        });

        modelBuilder.Entity<FinalQualification>(entity =>
        {
            entity.HasKey(e => e.QualificationId).HasName("PK__FinalQua__C95C128A6794CBA6");

            entity.Property(e => e.QualificationId).HasColumnName("QualificationID");
            entity.Property(e => e.GroupId).HasColumnName("GroupID");
            entity.Property(e => e.PhaseId).HasColumnName("PhaseID");
            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.TrackId).HasColumnName("TrackID");

            entity.HasOne(d => d.Group).WithMany(p => p.FinalQualifications)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Phase).WithMany(p => p.FinalQualifications)
                .HasForeignKey(d => d.PhaseId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Team).WithMany(p => p.FinalQualifications)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Track).WithMany(p => p.FinalQualifications)
                .HasForeignKey(d => d.TrackId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Group>(entity =>
        {
            entity.HasKey(e => e.GroupId).HasName("PK__Groups__149AF30A4AB40CD2");

            entity.Property(e => e.GroupId).HasColumnName("GroupID");
            entity.Property(e => e.GroupName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TrackId).HasColumnName("TrackID");

            entity.HasOne(d => d.Track).WithMany(p => p.Groups)
                .HasForeignKey(d => d.TrackId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<GroupTeam>(entity =>
        {
            entity.HasKey(e => e.GroupTeamId).HasName("PK__GroupTea__4A9DC8BC82E34907");

            entity.Property(e => e.GroupTeamId).HasColumnName("GroupTeamID");
            entity.Property(e => e.AverageScore).HasColumnType("decimal(6, 2)");
            entity.Property(e => e.GroupId).HasColumnName("GroupID");
            entity.Property(e => e.TeamId).HasColumnName("TeamID");

            entity.HasOne(d => d.Group).WithMany(p => p.GroupTeams)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Team).WithMany(p => p.GroupTeams)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Hackathon>(entity =>
        {
            entity.HasKey(e => e.HackathonId).HasName("PK__Hackatho__A9C9EEEB8EF36FE7");

            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.SeasonId).HasColumnName("SeasonID");
            entity.Property(e => e.Status).HasMaxLength(50);

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Hackathons)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Season).WithMany(p => p.Hackathons)
                .HasForeignKey(d => d.SeasonId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<HackathonPhase>(entity =>
        {
            entity.HasKey(e => e.PhaseId).HasName("PK__Hackatho__5BA26D42FF4BFDB7");

            entity.Property(e => e.PhaseId).HasColumnName("PhaseID");
            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.PhaseName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Hackathon).WithMany(p => p.HackathonPhases)
                .HasForeignKey(d => d.HackathonId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<HackathonRegistration>(entity =>
        {
            entity.HasKey(e => e.RegistrationId).HasName("PK__Hackatho__6EF58830C147FD9E");

            entity.Property(e => e.RegistrationId).HasColumnName("RegistrationID");
            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.TeamId).HasColumnName("TeamID");

            entity.HasOne(d => d.Hackathon).WithMany(p => p.HackathonRegistrations)
                .HasForeignKey(d => d.HackathonId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Team).WithMany(p => p.HackathonRegistrations)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<JudgeAssignment>(entity =>
        {
            entity.HasKey(e => e.AssignmentId).HasName("PK__JudgeAss__32499E57FEC670EA");

            entity.Property(e => e.AssignmentId).HasColumnName("AssignmentID");
            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.JudgeId).HasColumnName("JudgeID");
            entity.Property(e => e.PhaseId).HasColumnName("PhaseID");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.TrackId).HasColumnName("TrackID");

            entity.HasOne(d => d.Hackathon).WithMany(p => p.JudgeAssignments)
                .HasForeignKey(d => d.HackathonId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Judge).WithMany(p => p.JudgeAssignments)
                .HasForeignKey(d => d.JudgeId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Phase).WithMany(p => p.JudgeAssignments).HasForeignKey(d => d.PhaseId);

            entity.HasOne(d => d.Track).WithMany(p => p.JudgeAssignments).HasForeignKey(d => d.TrackId);
        });

        modelBuilder.Entity<MentorAssignment>(entity =>
        {
            entity.HasKey(e => e.AssignmentId).HasName("PK__MentorAs__32499E57E0EC659A");

            entity.Property(e => e.AssignmentId).HasColumnName("AssignmentID");
            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.MentorId).HasColumnName("MentorID");
            entity.Property(e => e.Status).HasMaxLength(20);
            entity.Property(e => e.TeamId).HasColumnName("TeamID");

            entity.HasOne(d => d.Hackathon).WithMany(p => p.MentorAssignments)
                .HasForeignKey(d => d.HackathonId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Mentor).WithMany(p => p.MentorAssignments)
                .HasForeignKey(d => d.MentorId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Team).WithMany(p => p.MentorAssignments)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<MentorVerification>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MentorVe__3214EC07189D92F5");

            entity.ToTable("MentorVerification");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Cv).HasColumnName("CV");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Position).HasMaxLength(255);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.Chapter).WithMany(p => p.MentorVerifications)
                .HasForeignKey(d => d.ChapterId)
                .HasConstraintName("FK_MentorVerification_Chapter");

            entity.HasOne(d => d.Hackathon).WithMany(p => p.MentorVerifications)
                .HasForeignKey(d => d.HackathonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MentorVerification_Hackathon");

            entity.HasOne(d => d.User).WithMany(p => p.MentorVerifications)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MentorVerification_User");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__Notifica__20CF2E326E379965");

            entity.Property(e => e.NotificationId).HasColumnName("NotificationID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<PartnerProfile>(entity =>
        {
            entity.HasKey(e => e.PartnerProfileId).HasName("PK__PartnerP__886A31EE7BFE95CF");

            entity.Property(e => e.PartnerProfileId).HasColumnName("PartnerProfileID");
            entity.Property(e => e.CompanyName).HasMaxLength(255);
            entity.Property(e => e.LogoUrl).HasMaxLength(500);
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Website).HasMaxLength(255);

            entity.HasOne(d => d.User).WithMany(p => p.PartnerProfiles)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<PenaltiesBonuse>(entity =>
        {
            entity.HasKey(e => e.AdjustmentId).HasName("PK__Penaltie__E60DB8B381DC17A4");

            entity.Property(e => e.AdjustmentId).HasColumnName("AdjustmentID");
            entity.Property(e => e.Points).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.PenaltiesBonuses)
                .HasForeignKey(d => d.CreatedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PenaltiesBonuses_CreatedBy");

            entity.HasOne(d => d.Phase).WithMany(p => p.PenaltiesBonuses)
                .HasForeignKey(d => d.PhaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PenaltiesBonuses_Phase");

            entity.HasOne(d => d.Team).WithMany(p => p.PenaltiesBonuses)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Prize>(entity =>
        {
            entity.HasKey(e => e.PrizeId).HasName("PK__Prizes__5C36F4BB8E89EB13");

            entity.Property(e => e.PrizeId).HasColumnName("PrizeID");
            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.PrizeName).HasMaxLength(100);
            entity.Property(e => e.PrizeType).HasMaxLength(50);

            entity.HasOne(d => d.Hackathon).WithMany(p => p.Prizes)
                .HasForeignKey(d => d.HackathonId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<PrizeAllocation>(entity =>
        {
            entity.HasKey(e => e.AllocationId).HasName("PK__PrizeAll__B3C6D6AB9C6FA0B7");

            entity.Property(e => e.AllocationId).HasColumnName("AllocationID");
            entity.Property(e => e.PrizeId).HasColumnName("PrizeID");
            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Prize).WithMany(p => p.PrizeAllocations)
                .HasForeignKey(d => d.PrizeId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Team).WithMany(p => p.PrizeAllocations).HasForeignKey(d => d.TeamId);

            entity.HasOne(d => d.User).WithMany(p => p.PrizeAllocations)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity<Ranking>(entity =>
        {
            entity.HasKey(e => e.RankingId).HasName("PK__Rankings__018A6AF9A8914E2B");

            entity.Property(e => e.RankingId).HasColumnName("RankingID");
            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.TotalScore).HasColumnType("decimal(6, 2)");

            entity.HasOne(d => d.Hackathon).WithMany(p => p.Rankings)
                .HasForeignKey(d => d.HackathonId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Team).WithMany(p => p.Rankings)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE3AB3480D26");

            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<ScheduleEvent>(entity =>
        {
            entity.HasKey(e => e.EventId).HasName("PK__Schedule__7944C870C8306164");

            entity.Property(e => e.EventId).HasColumnName("EventID");
            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.Location).HasMaxLength(255);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.PhaseId).HasColumnName("PhaseID");
            entity.Property(e => e.Type).HasMaxLength(50);

            entity.HasOne(d => d.Hackathon).WithMany(p => p.ScheduleEvents)
                .HasForeignKey(d => d.HackathonId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Phase).WithMany(p => p.ScheduleEvents).HasForeignKey(d => d.PhaseId);
        });

        modelBuilder.Entity<Score>(entity =>
        {
            entity.HasKey(e => e.ScoreId).HasName("PK__Scores__7DD229F1CC12CDE6");

            entity.Property(e => e.ScoreId).HasColumnName("ScoreID");
            entity.Property(e => e.CriteriaId).HasColumnName("CriteriaID");
            entity.Property(e => e.JudgeId).HasColumnName("JudgeID");
            entity.Property(e => e.Score1)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("Score");
            entity.Property(e => e.SubmissionId).HasColumnName("SubmissionID");

            entity.HasOne(d => d.Criteria).WithMany(p => p.Scores)
                .HasForeignKey(d => d.CriteriaId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Judge).WithMany(p => p.Scores)
                .HasForeignKey(d => d.JudgeId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Submission).WithMany(p => p.Scores)
                .HasForeignKey(d => d.SubmissionId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<ScoreHistory>(entity =>
        {
            entity.HasKey(e => e.HistoryId).HasName("PK__ScoreHis__4D7B4ABDBE331A6B");

            entity.ToTable("ScoreHistory");

            entity.Property(e => e.ChangeReason).HasMaxLength(500);

            entity.HasOne(d => d.Criteria).WithMany(p => p.ScoreHistories)
                .HasForeignKey(d => d.CriteriaId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Judge).WithMany(p => p.ScoreHistories)
                .HasForeignKey(d => d.JudgeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ScoreHistory_Users_UserId");

            entity.HasOne(d => d.Score).WithMany(p => p.ScoreHistories)
                .HasForeignKey(d => d.ScoreId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Submission).WithMany(p => p.ScoreHistories)
                .HasForeignKey(d => d.SubmissionId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Season>(entity =>
        {
            entity.HasKey(e => e.SeasonId).HasName("PK__Season__C1814E184AB3E147");

            entity.ToTable("Season");

            entity.Property(e => e.SeasonId).HasColumnName("SeasonID");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<StudentVerification>(entity =>
        {
            entity.HasKey(e => e.VerificationId).HasName("PK__StudentV__306D4907C424B90D");

            entity.Property(e => e.BackCardImage).HasMaxLength(500);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.FrontCardImage).HasMaxLength(500);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Major).HasMaxLength(255);
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.StudentCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.StudentEmail)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UniversityName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.StudentVerifications)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Submission>(entity =>
        {
            entity.HasKey(e => e.SubmissionId).HasName("PK__Submissi__449EE1053ECC45AC");

            entity.Property(e => e.SubmissionId).HasColumnName("SubmissionID");
            entity.Property(e => e.PhaseId).HasColumnName("PhaseID");
            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.Title).HasMaxLength(200);

            entity.HasOne(d => d.Phase).WithMany(p => p.Submissions)
                .HasForeignKey(d => d.PhaseId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.SubmittedByNavigation).WithMany(p => p.Submissions)
                .HasForeignKey(d => d.SubmittedBy)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Team).WithMany(p => p.Submissions)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Team>(entity =>
        {
            entity.HasKey(e => e.TeamId).HasName("PK__Teams__123AE7B950743E41");

            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.ChapterId).HasColumnName("ChapterID");
            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.TeamLeaderId).HasColumnName("TeamLeaderID");
            entity.Property(e => e.TeamName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Chapter).WithMany(p => p.Teams)
                .HasForeignKey(d => d.ChapterId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Hackathon).WithMany(p => p.Teams).HasForeignKey(d => d.HackathonId);

            entity.HasOne(d => d.TeamLeader).WithMany(p => p.Teams)
                .HasForeignKey(d => d.TeamLeaderId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<TeamInvitation>(entity =>
        {
            entity.HasKey(e => e.InvitationId).HasName("PK__TeamInvi__033C8D2FC8A99D5C");

            entity.Property(e => e.InvitationId)
                .ValueGeneratedNever()
                .HasColumnName("InvitationID");
            entity.Property(e => e.InvitedByUserId).HasColumnName("InvitedByUserID");
            entity.Property(e => e.InvitedEmail).IsRequired();
            entity.Property(e => e.Status).HasMaxLength(20);
            entity.Property(e => e.TeamId).HasColumnName("TeamID");

            entity.HasOne(d => d.InvitedByUser).WithMany(p => p.TeamInvitations)
                .HasForeignKey(d => d.InvitedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Team).WithMany(p => p.TeamInvitations)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<TeamJoinRequest>(entity =>
        {
            entity.HasKey(e => e.RequestId).HasName("PK__TeamJoin__33A8519A7E7CB240");

            entity.Property(e => e.RequestId).HasColumnName("RequestID");
            entity.Property(e => e.LeaderResponse).HasMaxLength(500);
            entity.Property(e => e.Message).HasMaxLength(500);
            entity.Property(e => e.Status).HasMaxLength(20);
            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamJoinRequests)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.User).WithMany(p => p.TeamJoinRequests)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<TeamMember>(entity =>
        {
            entity.HasKey(e => new { e.TeamId, e.UserId }).HasName("PK__TeamMemb__C3426B73A2F999A7");

            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.RoleInTeam).HasMaxLength(50);

            entity.HasOne(d => d.Team).WithMany(p => p.TeamMembers)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.User).WithMany(p => p.TeamMembers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<TeamTrackSelection>(entity =>
        {
            entity.HasKey(e => e.TeamTrackSelectionId).HasName("PK__TeamTrac__84FCC0CC6740DD1B");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamTrackSelections)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TeamTrackSelections_Teams_TeamID");

            entity.HasOne(d => d.Track).WithMany(p => p.TeamTrackSelections)
                .HasForeignKey(d => d.TrackId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TeamTrackSelections_Tracks_TrackID");
        });

        modelBuilder.Entity<Track>(entity =>
        {
            entity.HasKey(e => e.TrackId).HasName("PK__Tracks__7A74F8C0D39036CB");

            entity.Property(e => e.TrackId).HasColumnName("TrackID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PhaseId).HasColumnName("PhaseID");

            entity.HasOne(d => d.Phase).WithMany(p => p.Tracks)
                .HasForeignKey(d => d.PhaseId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCACD2A16B32");

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PasswordHash).IsRequired();
            entity.Property(e => e.RefreshTokenExpiryTime).HasColumnType("datetime");
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.Token).HasMaxLength(255);

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.SetNull);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}