// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Repositories.Models;

public partial class SealDbContext : DbContext
{
    public SealDbContext(DbContextOptions<SealDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Appeal> Appeals { get; set; }

    public virtual DbSet<AuditLog> AuditLogs { get; set; }

    public virtual DbSet<Challenge> Challenges { get; set; }

    public virtual DbSet<Chapter> Chapters { get; set; }

    public virtual DbSet<Criterion> Criteria { get; set; }

    public virtual DbSet<CriterionDetail> CriterionDetails { get; set; }

    public virtual DbSet<FinalQualification> FinalQualifications { get; set; }

    public virtual DbSet<Group> Groups { get; set; }

    public virtual DbSet<GroupTeam> GroupTeams { get; set; }

    public virtual DbSet<Hackathon> Hackathons { get; set; }

    public virtual DbSet<HackathonPhase> HackathonPhases { get; set; }

    public virtual DbSet<MentorAssignment> MentorAssignments { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<PenaltiesBonuse> PenaltiesBonuses { get; set; }

    public virtual DbSet<Prize> Prizes { get; set; }

    public virtual DbSet<PrizeAllocation> PrizeAllocations { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<ScheduleEvent> ScheduleEvents { get; set; }

    public virtual DbSet<Score> Scores { get; set; }

    public virtual DbSet<Season> Seasons { get; set; }

    public virtual DbSet<StudentVerification> StudentVerifications { get; set; }

    public virtual DbSet<Submission> Submissions { get; set; }

    public virtual DbSet<Team> Teams { get; set; }

    public virtual DbSet<TeamInvitation> TeamInvitations { get; set; }

    public virtual DbSet<TeamJoinRequest> TeamJoinRequests { get; set; }

    public virtual DbSet<TeamMember> TeamMembers { get; set; }

    public virtual DbSet<TeamTrackSelection> TeamTrackSelections { get; set; }

    public virtual DbSet<Track> Tracks { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Appeal>(entity =>
        {
            entity.HasKey(e => e.AppealId).HasName("PK__Appeals__BB6849F0C2B1C61C");

            entity.Property(e => e.AppealType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Message).IsRequired();
            entity.Property(e => e.Status).IsRequired();

            entity.HasOne(d => d.Adjustment).WithMany(p => p.Appeals)
                .HasForeignKey(d => d.AdjustmentId)
                .OnDelete(DeleteBehavior.SetNull);

            entity.HasOne(d => d.ReviewedBy).WithMany(p => p.Appeals)
                .HasForeignKey(d => d.ReviewedById)
                .OnDelete(DeleteBehavior.SetNull);

            entity.HasOne(d => d.Score).WithMany(p => p.Appeals).HasForeignKey(d => d.ScoreId);

            entity.HasOne(d => d.Team).WithMany(p => p.Appeals)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<AuditLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__AuditLog__5E5499A899787792");

            entity.Property(e => e.LogId).HasColumnName("LogID");
            entity.Property(e => e.Action)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.AuditLogs)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity<Challenge>(entity =>
        {
            entity.HasKey(e => e.ChallengeId).HasName("PK__Challeng__C7AC81280B2BF475");

            entity.Property(e => e.ChallengeId).HasColumnName("ChallengeID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.FilePath).HasMaxLength(255);
            entity.Property(e => e.Status).IsRequired();
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.Challenges)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Chapter>(entity =>
        {
            entity.HasKey(e => e.ChapterId).HasName("PK__Chapters__0893A34A430B6684");

            entity.Property(e => e.ChapterId).HasColumnName("ChapterID");
            entity.Property(e => e.ChapterLeaderId).HasColumnName("ChapterLeaderID");
            entity.Property(e => e.ChapterName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
        });

        modelBuilder.Entity<Criterion>(entity =>
        {
            entity.HasKey(e => e.CriteriaId).HasName("PK__Criteria__FE6ADB2DDC4961E2");

            entity.Property(e => e.CriteriaId).HasColumnName("CriteriaID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PhaseId).HasColumnName("PhaseID");
            entity.Property(e => e.Weight).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Phase).WithMany(p => p.Criteria)
                .HasForeignKey(d => d.PhaseId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<CriterionDetail>(entity =>
        {
            entity.HasKey(e => e.CriterionDetailId).HasName("PK__Criterio__137EE6E075C942E3");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Criteria).WithMany(p => p.CriterionDetails)
                .HasForeignKey(d => d.CriteriaId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<FinalQualification>(entity =>
        {
            entity.HasKey(e => e.QualificationId).HasName("PK__FinalQua__C95C12AA23742760");

            entity.Property(e => e.Name).HasMaxLength(100);

            entity.HasOne(d => d.Group).WithMany(p => p.FinalQualifications)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Phase).WithMany(p => p.FinalQualifications)
                .HasForeignKey(d => d.PhaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FinalQualifications_HackathonPhases_PhaseID");

            entity.HasOne(d => d.Team).WithMany(p => p.FinalQualifications)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_FinalQualifications_Teams_TeamID");

            entity.HasOne(d => d.Track).WithMany(p => p.FinalQualifications)
                .HasForeignKey(d => d.TrackId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Group>(entity =>
        {
            entity.HasKey(e => e.GroupId).HasName("PK__Groups__149AF36A6D6479B1");

            entity.Property(e => e.GroupName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<GroupTeam>(entity =>
        {
            entity.HasKey(e => e.GroupTeamId).HasName("PK__GroupTea__4A9DC89C07C04482");

            entity.HasOne(d => d.Group).WithMany(p => p.GroupTeams)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Team).WithMany(p => p.GroupTeams)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Hackathon>(entity =>
        {
            entity.HasKey(e => e.HackathonId).HasName("PK__Hackatho__A9C9EEEB231CFE2A");

            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.SeasonId).HasColumnName("SeasonID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Theme).HasMaxLength(200);

            entity.HasOne(d => d.Season).WithMany(p => p.Hackathons)
                .HasForeignKey(d => d.SeasonId)
                .HasConstraintName("FK_Hackathons_Seasons_SeasonID");
        });

        modelBuilder.Entity<HackathonPhase>(entity =>
        {
            entity.HasKey(e => e.PhaseId).HasName("PK__Hackatho__5BA26D423F180216");

            entity.Property(e => e.PhaseId).HasColumnName("PhaseID");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.PhaseName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.StartDate).HasColumnType("datetime");

            entity.HasOne(d => d.Hackathon).WithMany(p => p.HackathonPhases).HasForeignKey(d => d.HackathonId);
        });

        modelBuilder.Entity<MentorAssignment>(entity =>
        {
            entity.HasKey(e => e.AssignmentId).HasName("PK__MentorAs__32499E57A88CEFA6");

            entity.Property(e => e.AssignmentId).HasColumnName("AssignmentID");
            entity.Property(e => e.AssignedAt).HasColumnType("datetime");
            entity.Property(e => e.ChapterId).HasColumnName("ChapterID");
            entity.Property(e => e.MentorId).HasColumnName("MentorID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.TeamId).HasColumnName("TeamID");

            entity.HasOne(d => d.Chapter).WithMany(p => p.MentorAssignments)
                .HasForeignKey(d => d.ChapterId)
                .OnDelete(DeleteBehavior.SetNull);

            entity.HasOne(d => d.Mentor).WithMany(p => p.MentorAssignments)
                .HasForeignKey(d => d.MentorId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Team).WithMany(p => p.MentorAssignments)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__Notifica__20CF2E322537A6F9");

            entity.Property(e => e.NotificationId).HasColumnName("NotificationID");
            entity.Property(e => e.Message).IsRequired();
            entity.Property(e => e.SentAt).HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<PenaltiesBonuse>(entity =>
        {
            entity.HasKey(e => e.AdjustmentId).HasName("PK__Penaltie__E60DB8B3732D54DA");

            entity.Property(e => e.AdjustmentId).HasColumnName("AdjustmentID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Points).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.Type).HasMaxLength(20);

            entity.HasOne(d => d.Team).WithMany(p => p.PenaltiesBonuses).HasForeignKey(d => d.TeamId);
        });

        modelBuilder.Entity<Prize>(entity =>
        {
            entity.HasKey(e => e.PrizeId).HasName("PK__Prizes__5C36F4BB4E46F545");

            entity.Property(e => e.PrizeId).HasColumnName("PrizeID");
            entity.Property(e => e.HackathonId).HasColumnName("HackathonID");
            entity.Property(e => e.PrizeName).HasMaxLength(100);
            entity.Property(e => e.PrizeType).HasMaxLength(50);

            entity.HasOne(d => d.Hackathon).WithMany(p => p.Prizes).HasForeignKey(d => d.HackathonId);
        });

        modelBuilder.Entity<PrizeAllocation>(entity =>
        {
            entity.HasKey(e => e.AllocationId).HasName("PK__PrizeAll__B3C6D6ABEA5DA1CB");

            entity.Property(e => e.AllocationId).HasColumnName("AllocationID");
            entity.Property(e => e.AwardedAt).HasColumnType("datetime");
            entity.Property(e => e.PrizeId).HasColumnName("PrizeID");
            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Prize).WithMany(p => p.PrizeAllocations).HasForeignKey(d => d.PrizeId);

            entity.HasOne(d => d.Team).WithMany(p => p.PrizeAllocations).HasForeignKey(d => d.TeamId);

            entity.HasOne(d => d.User).WithMany(p => p.PrizeAllocations)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE3A65063656");

            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<ScheduleEvent>(entity =>
        {
            entity.HasKey(e => e.EventId).HasName("PK__Schedule__7944C810AD48433A");

            entity.Property(e => e.Location).HasMaxLength(255);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.Type).HasMaxLength(50);

            entity.HasOne(d => d.Hackathon).WithMany(p => p.ScheduleEvents)
                .HasForeignKey(d => d.HackathonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ScheduleEvents_Hackathons_HackathonID");

            entity.HasOne(d => d.Phase).WithMany(p => p.ScheduleEvents)
                .HasForeignKey(d => d.PhaseId)
                .HasConstraintName("FK_ScheduleEvents_HackathonPhases_PhaseID");
        });

        modelBuilder.Entity<Score>(entity =>
        {
            entity.HasKey(e => e.ScoreId).HasName("PK__Scores__7DD229F143E34A03");

            entity.Property(e => e.ScoreId).HasColumnName("ScoreID");
            entity.Property(e => e.CriteriaId).HasColumnName("CriteriaID");
            entity.Property(e => e.JudgeId).HasColumnName("JudgeID");
            entity.Property(e => e.Score1)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("Score");
            entity.Property(e => e.ScoredAt).HasColumnType("datetime");
            entity.Property(e => e.SubmissionId).HasColumnName("SubmissionID");

            entity.HasOne(d => d.Criteria).WithMany(p => p.Scores)
                .HasForeignKey(d => d.CriteriaId)
                .OnDelete(DeleteBehavior.SetNull);

            entity.HasOne(d => d.Judge).WithMany(p => p.Scores)
                .HasForeignKey(d => d.JudgeId)
                .OnDelete(DeleteBehavior.SetNull);

            entity.HasOne(d => d.Submission).WithMany(p => p.Scores).HasForeignKey(d => d.SubmissionId);
        });

        modelBuilder.Entity<Season>(entity =>
        {
            entity.HasKey(e => e.SeasonId).HasName("PK__Season__C1814E18F085A371");

            entity.ToTable("Season");

            entity.Property(e => e.SeasonId).HasColumnName("SeasonID");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<StudentVerification>(entity =>
        {
            entity.HasKey(e => e.VerificationId).HasName("PK__StudentV__306D490778156909");

            entity.Property(e => e.BackCardImage).HasMaxLength(500);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.FrontCardImage).HasMaxLength(500);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Major).HasMaxLength(255);
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.StudentCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.StudentEmail)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UniversityName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.User).WithMany(p => p.StudentVerifications)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Submission>(entity =>
        {
            entity.HasKey(e => e.SubmissionId).HasName("PK__Submissi__449EE1058933D939");

            entity.Property(e => e.SubmissionId).HasColumnName("SubmissionID");
            entity.Property(e => e.SubmittedAt).HasColumnType("datetime");
            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.Title).HasMaxLength(200);

            entity.HasOne(d => d.SubmittedByNavigation).WithMany(p => p.Submissions)
                .HasForeignKey(d => d.SubmittedBy)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Team).WithMany(p => p.Submissions).HasForeignKey(d => d.TeamId);
        });

        modelBuilder.Entity<Team>(entity =>
        {
            entity.HasKey(e => e.TeamId).HasName("PK__Teams__123AE7B9DBD76992");

            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.ChapterId).HasColumnName("ChapterID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.TeamLeaderId).HasColumnName("TeamLeaderID");
            entity.Property(e => e.TeamName)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Chapter).WithMany(p => p.Teams).HasForeignKey(d => d.ChapterId);

            entity.HasOne(d => d.TeamLeader).WithMany(p => p.Teams)
                .HasForeignKey(d => d.TeamLeaderId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<TeamInvitation>(entity =>
        {
            entity.HasKey(e => e.InvitationId).HasName("PK__TeamInvi__033C8DCFDEA29E42");

            entity.Property(e => e.InvitationId).ValueGeneratedNever();
            entity.Property(e => e.InvitedEmail).IsRequired();
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.InvitedByUser).WithMany(p => p.TeamInvitations)
                .HasForeignKey(d => d.InvitedByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Team).WithMany(p => p.TeamInvitations)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<TeamJoinRequest>(entity =>
        {
            entity.HasKey(e => e.RequestId).HasName("PK__TeamJoin__33A8519AC173334E");

            entity.Property(e => e.RequestId).HasColumnName("RequestID");
            entity.Property(e => e.LeaderResponse).HasMaxLength(500);
            entity.Property(e => e.Message).HasMaxLength(500);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamJoinRequests).HasForeignKey(d => d.TeamId);

            entity.HasOne(d => d.User).WithMany(p => p.TeamJoinRequests)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<TeamMember>(entity =>
        {
            entity.HasKey(e => new { e.TeamId, e.UserId }).HasName("PK__TeamMemb__C3426B7373A51804");

            entity.Property(e => e.TeamId).HasColumnName("TeamID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.RoleInTeam).HasMaxLength(50);

            entity.HasOne(d => d.Team).WithMany(p => p.TeamMembers).HasForeignKey(d => d.TeamId);

            entity.HasOne(d => d.User).WithMany(p => p.TeamMembers)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<TeamTrackSelection>(entity =>
        {
            entity.HasKey(e => e.TeamTrackSelectionId).HasName("PK__TeamTrac__84FCC0CCA4A412A2");

            entity.HasOne(d => d.Team).WithMany(p => p.TeamTrackSelections)
                .HasForeignKey(d => d.TeamId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Track).WithMany(p => p.TeamTrackSelections)
                .HasForeignKey(d => d.TrackId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Track>(entity =>
        {
            entity.HasKey(e => e.TrackId).HasName("PK__Tracks__7A74F8E0B8CFECFA");

            entity.Property(e => e.Name).HasMaxLength(100);

            entity.HasOne(d => d.Challenge).WithMany(p => p.Tracks).HasForeignKey(d => d.ChallengeId);

            entity.HasOne(d => d.Phase).WithMany(p => p.Tracks)
                .HasForeignKey(d => d.PhaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Tracks_HackathonPhases_PhaseID");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCAC6F2BBBAC");

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.RefreshTokenExpiryTime).HasColumnType("datetime");
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.Token).HasMaxLength(255);

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.SetNull);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}