// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class StudentVerification
{
    public int VerificationId { get; set; }

    public int UserId { get; set; }

    public string UniversityName { get; set; }

    public string StudentEmail { get; set; }

    public string StudentCode { get; set; }

    public int YearOfAdmission { get; set; }

    public string FullName { get; set; }

    public string Major { get; set; }

    public string FrontCardImage { get; set; }

    public string BackCardImage { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User User { get; set; }
}