// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Submission
{
    public int SubmissionId { get; set; }

    public int? TeamId { get; set; }

    public string Title { get; set; }

    public string GitHubLink { get; set; }

    public string DemoLink { get; set; }

    public string ReportLink { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public int PhaseChallengeId { get; set; }

    public int SubmittedBy { get; set; }

    public bool IsFinal { get; set; }

    public virtual ICollection<Score> Scores { get; set; } = new List<Score>();

    public virtual User SubmittedByNavigation { get; set; }

    public virtual Team Team { get; set; }
}