// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class TeamInvitation
{
    public Guid InvitationId { get; set; }

    public int TeamId { get; set; }

    public string InvitedEmail { get; set; }

    public int InvitedByUserId { get; set; }

    public Guid? InvitationCode { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public string Status { get; set; }

    public virtual User InvitedByUser { get; set; }

    public virtual Team Team { get; set; }
}