// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class TeamTrackSelection
{
    public int TeamTrackSelectionId { get; set; }

    public int TeamId { get; set; }

    public int TrackId { get; set; }

    public DateTime SelectedAt { get; set; }

    public virtual Team Team { get; set; }

    public virtual Track Track { get; set; }
}