// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class TeamJoinRequest
{
    public int RequestId { get; set; }

    public int TeamId { get; set; }

    public int UserId { get; set; }

    public string Message { get; set; }

    public string Status { get; set; }

    public string LeaderResponse { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? RespondedAt { get; set; }

    public virtual Team Team { get; set; }

    public virtual User User { get; set; }
}