// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Team
{
    public int TeamId { get; set; }

    public int HackathonId { get; set; }

    public int ChapterId { get; set; }

    public string TeamName { get; set; }

    public int TeamLeaderId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Appeal> Appeals { get; set; } = new List<Appeal>();

    public virtual Chapter Chapter { get; set; }

    public virtual ICollection<FinalQualification> FinalQualifications { get; set; } = new List<FinalQualification>();

    public virtual ICollection<GroupTeam> GroupTeams { get; set; } = new List<GroupTeam>();

    public virtual Hackathon Hackathon { get; set; }

    public virtual ICollection<HackathonRegistration> HackathonRegistrations { get; set; } = new List<HackathonRegistration>();

    public virtual ICollection<MentorAssignment> MentorAssignments { get; set; } = new List<MentorAssignment>();

    public virtual ICollection<PenaltiesBonuse> PenaltiesBonuses { get; set; } = new List<PenaltiesBonuse>();

    public virtual ICollection<PrizeAllocation> PrizeAllocations { get; set; } = new List<PrizeAllocation>();

    public virtual ICollection<Ranking> Rankings { get; set; } = new List<Ranking>();

    public virtual ICollection<Submission> Submissions { get; set; } = new List<Submission>();

    public virtual ICollection<TeamInvitation> TeamInvitations { get; set; } = new List<TeamInvitation>();

    public virtual ICollection<TeamJoinRequest> TeamJoinRequests { get; set; } = new List<TeamJoinRequest>();

    public virtual User TeamLeader { get; set; }

    public virtual ICollection<TeamMember> TeamMembers { get; set; } = new List<TeamMember>();

    public virtual ICollection<TeamTrackSelection> TeamTrackSelections { get; set; } = new List<TeamTrackSelection>();
}