// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Track
{
    public int TrackId { get; set; }

    public int PhaseId { get; set; }

    public int? ChallengeId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public virtual Challenge Challenge { get; set; }

    public virtual ICollection<Criterion> Criteria { get; set; } = new List<Criterion>();

    public virtual ICollection<FinalQualification> FinalQualifications { get; set; } = new List<FinalQualification>();

    public virtual ICollection<Group> Groups { get; set; } = new List<Group>();

    public virtual ICollection<JudgeAssignment> JudgeAssignments { get; set; } = new List<JudgeAssignment>();

    public virtual HackathonPhase Phase { get; set; }

    public virtual ICollection<TeamTrackSelection> TeamTrackSelections { get; set; } = new List<TeamTrackSelection>();
}